/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Importing.GoodsReceipt_Component;

import java.awt.Component;
import java.awt.FlowLayout;
import java.util.List;

/**
 *
 * @author PC
 */
public class GoodsReceiptList_Component extends javax.swing.JPanel {

    //private List<Product_Component> list;
    public GoodsReceiptList_Component() {
        initComponents();
        setLayout(new FlowLayout(FlowLayout.LEFT, 0, 10));
        //list = new ArrayList<>();
        //addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateData(List<GoodsReceipt_Component> list) {
        removeAll();
        //this.list = list;
        for (GoodsReceipt_Component product_Component : list) {
            add(product_Component);
        }

        repaint();
        revalidate();
    }

    public void changeStatusEditBtn(boolean b) {
        for (Component component : getComponents()) {
            if (component instanceof GoodsReceipt_Component) {
                ((GoodsReceipt_Component) component).changeStatusEditBtn(b);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
