/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Importing.ImportProduct.ImportProductDetails.Product_Component.Feature;

import java.text.DecimalFormat;

/**
 *
 * @author PC
 */
public class SubFeature_Component extends javax.swing.JPanel {

    /**
     * Creates new form ProductName_Component
     */
    public SubFeature_Component(double price, double discount) {
        initComponents();
        settings(price, discount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        finalPrice.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        finalPrice.setForeground(new java.awt.Color(0, 0, 0));
        finalPrice.setText("Paid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(finalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(finalPrice)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalPrice;
    // End of variables declaration//GEN-END:variables

    private void settings(double price, double discount) {
        finalPrice.setText(formatPrice(price));
    }

    public int getData() {
        return Integer.parseInt(finalPrice.getText().replace(",", ""));
    }

    private String formatPrice(double priceValue) {
        if (priceValue == 0) {
            return "0";
        }
        DecimalFormat formatter = new DecimalFormat("#,###");
        return formatter.format(priceValue);
    }
}
