/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Product.Filter;

import controller.Session.SharedData;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author PC
 */
public class Title extends javax.swing.JPanel {

    private JButton clearButton;
    private FilterItem parent;
    private String name;

    public Title(String titleName, FilterItem parent) {
        initComponents();
        this.parent = parent;
        this.name = titleName;
        setLayout(new BorderLayout());
        addComponents(titleName);
        addEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addComponents(String titleName) {
        JLabel hostLabel = new JLabel(titleName);
        hostLabel.setFont(new Font(SharedData.fontName, Font.BOLD, 22));  // Set custom font for bold style

        // Clear button with underline using HTML
        clearButton = new JButton("<html><u>Clear</u></html>");
        clearButton.setForeground(Color.GRAY); // Set text color to gray
        clearButton.setBorderPainted(false);  // Remove any painted border
        clearButton.setFocusPainted(false); // Disable focus painted border
        clearButton.setContentAreaFilled(false); // Remove button background
        clearButton.setOpaque(false); // Make button transparent
        clearButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR)); // Set hand cursor on hover
        clearButton.setFont(new Font(SharedData.fontName, Font.PLAIN, 14));

        // Add components to the main panel
        add(hostLabel, BorderLayout.WEST);  // Align "Host Language" to the left
        add(clearButton, BorderLayout.EAST);  // Align "Clear" button to the right

        // Add padding to the main panel
        setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
    }

    private void addEvents() {
        clearButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                parent.clear();
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public String getTitleName() {
        return name;
    }
}
