/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Order.Filter;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

/**
 *
 * @author PC
 */
public class FilterItem_Container extends javax.swing.JPanel {

    private List<FilterItem> list;
    private FilterItem orderStatus;

    public FilterItem_Container() {
        initComponents();
        setLayout(new GridLayout(0, 1, 10, 10));
        initData();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initData() {

        List<String> statusList = Arrays.asList("Packed", "Shipped", "Delivered");
        orderStatus = new FilterItem("Order Status", statusList);

    }

    private void addComponents() {
        list = new ArrayList<>();
        add(orderStatus);

        list.add(orderStatus);
    }

    public List<FilterItem> getAll() {
        return list;
    }

    public List<String> getSelectedItems() {
        // return the combined map
        return orderStatus.getSelectedItems();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
