/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Order.OrderDetails;

import java.awt.BorderLayout;
import javax.swing.border.EmptyBorder;
import model.Address;
import model.Bills;
import model.Customer;
import model.GoodsReceipt;
import model.OrderHistory;
import view.component.Order.OrderDetails.OrderDetailContent.OrderProductContent_Component;

/**
 *
 * @author PC
 */
public class OrderDetailsSouth_Component extends javax.swing.JPanel {

    private OrderProductContent_Component importProductContent_Component;
    private OrderSumary_Component importSumary_Component;
    private OrderDetailsPage_Component parent;

    public OrderDetailsSouth_Component(OrderDetailsPage_Component parent) {
        initComponents();

        this.parent = parent;
        setLayout(new BorderLayout(20, 0));
        setBorder(new EmptyBorder(15, 15, 15, 15));

        importSumary_Component = new OrderSumary_Component(this);
        importProductContent_Component = new OrderProductContent_Component(this);

        add(importSumary_Component, BorderLayout.EAST);
        add(importProductContent_Component, BorderLayout.CENTER);
    }

    public OrderDetailsSouth_Component(OrderDetailsPage_Component parent, Bills bills) {
        initComponents();

        this.parent = parent;
        setLayout(new BorderLayout(20, 0));
        setBorder(new EmptyBorder(15, 15, 15, 15));

        importSumary_Component = new OrderSumary_Component(this, bills);
        importProductContent_Component = new OrderProductContent_Component(this, bills);

        add(importSumary_Component, BorderLayout.EAST);
        add(importProductContent_Component, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateSumaryData(double price) {
        importSumary_Component.updateSumaryData(price);
    }

    public void updateTotal(double price) {
        importSumary_Component.updateTotal(price);
    }

    void updateImportProducts(Bills bills, Customer customer, Address address, OrderHistory orderHistory) {
        importProductContent_Component.updateImportProducts(bills, customer, address, orderHistory, importSumary_Component.getDeliveryFee(), importSumary_Component.getTotalPaid(), importSumary_Component.getDiscount(), importSumary_Component.getOtherDiscount(), importSumary_Component.getTotalPrice());
    }

    void unfulfilledOrder(Bills bills, Customer customer, Address address, OrderHistory orderHistory) {
        importProductContent_Component.unfulfilledOrder(bills, customer, address, orderHistory, importSumary_Component.getDeliveryFee(), importSumary_Component.getTotalPaid(), importSumary_Component.getDiscount(), importSumary_Component.getOtherDiscount(), importSumary_Component.getTotalPrice());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
