/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Order.OrderDetails;

import java.awt.BorderLayout;
import javax.swing.JDialog;
import model.Address;
import model.Bills;
import model.Customer;
import model.OrderHistory;
import view.component.Order.Pagination.Pagination_Component;

/**
 *
 * @author PC
 */
public class OrderDetailsPage_Component extends javax.swing.JPanel {

    private OrderDetailsSouth_Component orderDetailsSouth_Component;
    private OrderDetailsNorth_Component orderDetailsNorth_Component;
    private JDialog dialog;
    private OrderDetails_Component parent;
    private Pagination_Component paginationParent;
    private Bills bills;

    public OrderDetailsPage_Component(JDialog jDialog, OrderDetails_Component parent) {
        initComponents();

        this.parent = parent;
        this.dialog = jDialog;
        orderDetailsSouth_Component = new OrderDetailsSouth_Component(this);
        orderDetailsNorth_Component = new OrderDetailsNorth_Component(this);

        setLayout(new BorderLayout());
        add(orderDetailsSouth_Component, BorderLayout.CENTER);
        add(orderDetailsNorth_Component, BorderLayout.NORTH);
    }

    public OrderDetailsPage_Component(Pagination_Component paginationParent, Bills bills, JDialog addProductDialog) {
        initComponents();
        this.paginationParent = paginationParent;
        dialog = addProductDialog;
        this.bills = bills;

        orderDetailsSouth_Component = new OrderDetailsSouth_Component(this, bills);
        orderDetailsNorth_Component = new OrderDetailsNorth_Component(this, bills);

        setLayout(new BorderLayout());
        add(orderDetailsSouth_Component, BorderLayout.CENTER);
        add(orderDetailsNorth_Component, BorderLayout.NORTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void close() {
        if (dialog != null) {
            dialog.dispose();
        }
    }

    public void updateImportProducts(Bills bills) {
        Customer customer = orderDetailsNorth_Component.getCustomer();
        Address address = orderDetailsNorth_Component.getAddress();
        OrderHistory orderHistory = orderDetailsNorth_Component.getOrderHistory();
        orderDetailsSouth_Component.updateImportProducts(bills, customer, address, orderHistory);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
