/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Order.OrderDetails;

import view.component.Order.OrderDetails.OrderOtherConent.OrderHistory_Component;
import view.component.Order.OrderDetails.OrderOtherConent.DeliveryAddress_Component;
import view.component.Order.OrderDetails.OrderOtherConent.CustomerDetails_Component;
import java.awt.FlowLayout;
import java.sql.Date;
import javax.swing.border.EmptyBorder;
import model.Address;
import model.Bills;
import model.Customer;
import model.OrderHistory;

/**
 *
 * @author PC
 */
public class OrderDetailsNorth_Component extends javax.swing.JPanel {

    private CustomerDetails_Component customerDetails_Component;
    private DeliveryAddress_Component deliveryAddress_Component;
    private OrderHistory_Component orderHistory_Component;
    private Bills bills;

    private OrderDetailsPage_Component parent;

    public OrderDetailsNorth_Component(OrderDetailsPage_Component parent, Bills bills) {
        initComponents();
        this.parent = parent;
        this.bills = bills;
        setLayout(new FlowLayout(FlowLayout.LEFT, 35, 0));
        setBorder(new EmptyBorder(20, 0, 0, 0));
        
        customerDetails_Component = new CustomerDetails_Component(bills.getCustomer());
        deliveryAddress_Component = new DeliveryAddress_Component(bills.getCustomer());
        orderHistory_Component = new OrderHistory_Component(bills.getPaidDate(), bills.getPackedDate(), bills.getShippedDate(), bills.getDeliveredDate());

        add(customerDetails_Component);
        add(deliveryAddress_Component);
        add(orderHistory_Component);
    }

    public OrderDetailsNorth_Component(OrderDetailsPage_Component parent) {
        initComponents();
        this.parent = parent;
        setLayout(new FlowLayout(FlowLayout.LEFT, 35, 0));
        setBorder(new EmptyBorder(20, 0, 0, 0));

        customerDetails_Component = new CustomerDetails_Component();
        deliveryAddress_Component = new DeliveryAddress_Component();
        orderHistory_Component = new OrderHistory_Component();

        add(customerDetails_Component);
        add(deliveryAddress_Component);
        add(orderHistory_Component);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(248, 248, 248));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public Customer getCustomer() {
        String name = customerDetails_Component.getCustomerName();
        String phone = customerDetails_Component.getCustomerPhone();
        return new Customer(name, phone, true);
    }

    public Address getAddress() {
        String address = deliveryAddress_Component.getAddressLine();
        String distric = deliveryAddress_Component.getDistrict();
        String city = deliveryAddress_Component.getCity();
        String flat = deliveryAddress_Component.getFlatName();
        return new Address(address, distric, city, flat);
    }

    public OrderHistory getOrderHistory() {
        Date paidDate = orderHistory_Component.getPaidDate();
        Date packedDate = orderHistory_Component.getPackedDate();
        Date shippedDate = orderHistory_Component.getShippedDate();
        Date deliveredDate = orderHistory_Component.getDeliveredDate();
        return new OrderHistory(paidDate, packedDate, shippedDate, deliveredDate);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
