/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Order.OrderDetails.OderProductDetails.Header_Component;

import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import view.component.Btn.IconButton;
import view.component.Order.OrderDetails.OderProductDetails.OrderProductContent_Component;

import view.component.Product.PaginationWithSearchBar;

/**
 *
 * @author PC
 */
public class Header_Component extends javax.swing.JPanel {

    private boolean isEditing = false;
    private ImageIcon editIcon = new ImageIcon(getClass().getResource("/icon/edit.png"));
    private ImageIcon checkIcon = new ImageIcon(getClass().getResource("/icon/check.png"));
    private JButton editBtn;
    private JButton cancelBtn;
    private IconButton browseBtn;
    private OrderProductContent_Component parent;

    public Header_Component(OrderProductContent_Component parent) {
        initComponents();
        this.parent = parent;
        setLayout(new FlowLayout(FlowLayout.RIGHT, 10, 10));
        initData();
        customComponents();
        addEvents();
        addComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customComponents() {
        settings(editBtn);
        settings(cancelBtn);
        cancelBtn.setEnabled(false);
        browseBtn.setEnabled(false);
    }

    private void changeStatusComponents(String str) {
        if (isEditing) {
            editBtn.setIcon(checkIcon);
        } else {
            editBtn.setIcon(editIcon);
        }
        cancelBtn.setEnabled(isEditing);
        browseBtn.setEnabled(isEditing);
        parent.setEditable(str);
    }

    private void addComponents() {
        add(browseBtn);
        add(cancelBtn);
        add(editBtn);
    }

    private void initData() {
        editBtn = new JButton(editIcon);
        cancelBtn = new JButton(new javax.swing.ImageIcon(getClass().getResource("/icon/cancel2.png")));
        browseBtn = new IconButton("Browse", new ImageIcon(getClass().getResource("/icon/browse.png")), true);
    }

    private void settings(JButton btn) {
        btn.setBackground(new java.awt.Color(255, 255, 255));
        btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn.setBorderPainted(false);
        btn.setContentAreaFilled(false);
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.setFocusPainted(false);
    }

    private void addEvents() {
        editBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                isEditing = !isEditing;
                changeStatusComponents("Edit");
            }
        });

        cancelBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                isEditing = !isEditing;
                changeStatusComponents("Cancel");
            }
        });

        browseBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JDialog addProductDialog = new JDialog((Frame) null, "Edit Product", true);  // true for modal
                addProductDialog.setSize(1180, 700);
                addProductDialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);  // Close only the dialog
                addProductDialog.setLocationRelativeTo(null);  // Center the popup on screen
                //addProductDialog.setResizable(false);
                addProductDialog.add(new PaginationWithSearchBar(null, true));

                addProductDialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
