/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Order.OrderDetails.OderProductDetails.Product_Component.Feature;

/**
 *
 * @author PC
 */
public class SubFeature_Component extends javax.swing.JPanel {

    /**
     * Creates new form ProductName_Component
     */
    public SubFeature_Component(String text, boolean hasDiscount) {
        initComponents();
        this.finalPrice.setText(text);
        settings(hasDiscount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalPrice = new javax.swing.JLabel();
        origin = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        finalPrice.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        finalPrice.setForeground(new java.awt.Color(0, 0, 0));
        finalPrice.setText("Paid");

        origin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        origin.setForeground(new java.awt.Color(0, 0, 0));
        origin.setText("Paid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(finalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(origin, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(origin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finalPrice)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalPrice;
    private javax.swing.JLabel origin;
    // End of variables declaration//GEN-END:variables

    private void settings(boolean hasDiscount) {
        origin.setVisible(hasDiscount);
        if (hasDiscount) {
            String text = "<html><s> " + origin.getText() + "</s></html>";
            origin.setText(text);
        }
    }

}
