/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.MainFrame;

import controller.Functional.Functional;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.MatteBorder;
import view.component.Home.Home_Component;
import view.component.Navigation.Navigation;
import view.component.Product.ContentPage_Component;

/**
 *
 * @author PC
 */
public class MainContent_Component extends javax.swing.JPanel {
    
    private JPanel contentPanel; // Panel that holds different content pages
    private Navigation navigation;
    private JLabel logo;
    private JPanel nagigationPanel;
    
    public MainContent_Component() {
        initComponents();
        setLayout(new BorderLayout());
        
        nagigationPanel = new JPanel();
        nagigationPanel.setLayout(new BorderLayout());
        nagigationPanel.setBackground(new Color(253, 253, 253));
        
        navigation = new Navigation(this);
        navigation.setBorder(new MatteBorder(0, 0, 0, 1, new Color(240, 240, 240)));
        logo = new JLabel();
        logo.setSize(154, 90);
        ImageIcon icon = new ImageIcon(getClass().getResource("/logo/logo1.png"));
        logo.setIcon(Functional.scaleImg(logo, icon));
        
        nagigationPanel.add(logo, BorderLayout.NORTH);
        nagigationPanel.add(navigation, BorderLayout.CENTER);
        
        add(nagigationPanel, BorderLayout.WEST);
        
        contentPanel = new JPanel(new BorderLayout());
        
        contentPanel.add(new Home_Component());
        
        add(contentPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showContent(String name) {
        contentPanel.removeAll();
        switch (name) {
            case "Home":
                contentPanel.add(new Home_Component());
                break;
            case "Inventory":
                contentPanel.add(new ContentPage_Component());
                break;
            case "Importing":
                contentPanel.add(new view.component.Importing.ContentPage_Component());
                break;
            case "Order":
                contentPanel.add(new view.component.Order.ContentPage_Component());
                break;
            default:
                break;
        }
        contentPanel.revalidate();
        contentPanel.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
