/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.MainFrame;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;
import view.component.Home.Home_Component;
import view.component.Navigation.Navigation;
import view.component.Product.ContentPage_Component;

/**
 *
 * @author PC
 */
public class MainContent_Component extends javax.swing.JPanel {

    private CardLayout cardLayout; // CardLayout for switching content pages
    private JPanel contentPanel; // Panel that holds different content pages
    private Navigation navigation;

    public MainContent_Component() {
        initComponents();
        setLayout(new BorderLayout());

        navigation = new Navigation(this);

        add(navigation, BorderLayout.WEST);
        //add(new ContentPage_Component(), BorderLayout.CENTER);

        cardLayout = new CardLayout();
        //contentPanel = new JPanel(cardLayout);
        contentPanel = new JPanel(new BorderLayout());

        // Add multiple content pages to the card layout
        //contentPanel.add(new ContentPage_Component(), "Inventory");
        //contentPanel.add(new view.component.Importing.ContentPage_Component(), "Importing");
        contentPanel.add(new Home_Component());

        add(contentPanel, BorderLayout.CENTER);

        //contentPanel.add(new ContentPage3_Component(), "Importing");
        //contentPanel.add(new ContentPage4_Component(), "Invoice");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

//    public void showContent(String name) {
//        cardLayout.show(contentPanel, name);
//    }
    public void showContent(String name) {
        contentPanel.removeAll();
        switch (name) {
            case "Home":
                contentPanel.add(new Home_Component());
                break;
            case "Inventory":
                contentPanel.add(new ContentPage_Component());
                break;
            case "Importing":
                contentPanel.add(new view.component.Importing.ContentPage_Component());
                break;
            case "Order":
                contentPanel.add(new view.component.Order.ContentPage_Component());
                break;
            default:
                break;
        }
        contentPanel.revalidate();
        contentPanel.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
