/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component.Order.OrderDetails.OderProductDetails.Product_Component;

import controller.Functional.Functional;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import model.Product;
import view.component.Order.OrderDetails.OderProductDetails.Product_Component.Feature.ProductName_Component;
import view.component.Order.OrderDetails.OderProductDetails.Product_Component.Feature.OneFeature_Component;
import view.component.Order.OrderDetails.OderProductDetails.Product_Component.Feature.QuantityFeature_Component;
import view.component.Order.OrderDetails.OderProductDetails.Product_Component.Feature.SubFeature_Component;

/**
 *
 * @author PC
 */
public class Product_Component extends javax.swing.JPanel {

    private JButton deleteBtn;
    private Product product;
    private QuantityFeature_Component quantityFeature_Component;
    private SubFeature_Component subFeature_Component;
    private OneFeature_Component oneFeature_Component;
    private ProductList_Component parent;

    public Product_Component(Product product, ProductList_Component parent) {
        initComponents();
        this.parent = parent;
        this.product = product;
        setLayout(new FlowLayout(FlowLayout.LEFT, 15, 0));
        addComponents(product);
        customComponents();
        addEvents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.requestFocusInWindow();
    }//GEN-LAST:event_formMouseClicked

    private void addComponents(Product product) {

        ProductName_Component productName = new ProductName_Component(product.getName(), product.getCode(), Functional.convertByteArrayToIcon(product.getImg()));

        add(productName);

        List<String> features = new ArrayList<>();
        //"Brand", "Quantity", "Sale Price", "Discount", "Type", "Gender"

        quantityFeature_Component = new QuantityFeature_Component(product.getAmount() + "", this);
        add(quantityFeature_Component);

        subFeature_Component = new SubFeature_Component(product.getPrice() + "", true);
        add(subFeature_Component);

        oneFeature_Component = new OneFeature_Component(product.getPrice() + "");
        add(oneFeature_Component);

        deleteBtn = new JButton();
        add(deleteBtn);
    }

    private void addEvents() {
        deleteBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

    }

    public Product getProduct() {
        return product;
    }

    private String formatPrice(double priceValue) {
        if (priceValue == 0) {
            return "0";
        }
        DecimalFormat formatter = new DecimalFormat("#,###");
        return formatter.format(priceValue);
    }

    private void customComponents() {
        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bin.png"))); // NOI18N
        deleteBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteBtn.setBorderPainted(false);
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.setFocusPainted(false);
    }

    void setEditable(String str) {
        quantityFeature_Component.setEditable(str);
    }

    public void rollback() {
        parent.rollback();
    }

    public void storeData() {
        parent.storeData();
    }
    
    public String getData() {
        return quantityFeature_Component.getQuantity();
    }

    void setPrevData(String data) {
        quantityFeature_Component.setPrevData(data);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
